/*
 * Copyright 2017, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 * @file  al_hal_eth_mac_config_defs.h
 *
 * @brief mac_config macro definitons
 *
 */


#ifndef __AL_HAL_ETH_MAC_CONFIG_DEFS_H__
#define __AL_HAL_ETH_MAC_CONFIG_DEFS_H__

#include "al_hal_eth_mac_regs.h"

/*************************** mac_1g.cmd_cfg reg defs ***************************/

#define ETH_MAC_MAC_1G_CMD_CFG_TX_ENA		(1 << 0)
#define ETH_MAC_MAC_1G_CMD_CFG_RX_ENA		(1 << 1)
#define ETH_MAC_MAC_1G_CMD_CFG_ETH_SPEED	(1 << 3)
#define ETH_MAC_MAC_1G_CMD_CFG_PROMIS_EN	(1 << 4)
#define ETH_MAC_MAC_1G_CMD_CFG_CNTL_FRM_ENA	(1 << 23)
#define ETH_MAC_MAC_1G_CMD_CFG_NO_LGTH_CHECK	(1 << 24)


/**** gen.clk_cfg register ****/

#define AL_ETH_MAC_GEN_CLK_CFG_LANES_CLK_SEL(lane_3_clk_sel,		  \
					     lane_2_clk_sel,		  \
					     lane_1_clk_sel,		  \
					     lane_0_clk_sel)		  \
	((ETH_MAC_GEN_CLK_CFG_LANE_3_CLK_SEL_MASK &				\
	  ((lane_3_clk_sel) << ETH_MAC_GEN_CLK_CFG_LANE_3_CLK_SEL_SHIFT)) |	\
	 (ETH_MAC_GEN_CLK_CFG_LANE_2_CLK_SEL_MASK &				\
	  ((lane_2_clk_sel) << ETH_MAC_GEN_CLK_CFG_LANE_2_CLK_SEL_SHIFT)) |	\
	 (ETH_MAC_GEN_CLK_CFG_LANE_1_CLK_SEL_MASK &				\
	  ((lane_1_clk_sel) << ETH_MAC_GEN_CLK_CFG_LANE_1_CLK_SEL_SHIFT)) |	\
	 (ETH_MAC_GEN_CLK_CFG_LANE_0_CLK_SEL_MASK &				\
	  ((lane_0_clk_sel) << ETH_MAC_GEN_CLK_CFG_LANE_0_CLK_SEL_SHIFT)))

/**** gen.cfg register ****/

#define ETH_MAC_GEN_CFG_MAC_1_10_SHIFT		0
#define ETH_MAC_GEN_CFG_MAC_1_10_1G_MAC		(0 << ETH_MAC_GEN_CFG_MAC_1_10_SHIFT)
#define ETH_MAC_GEN_CFG_MAC_1_10_10_GMAC	(1 << ETH_MAC_GEN_CFG_MAC_1_10_SHIFT)

#define ETH_MAC_GEN_CFG_XGMII_SGMII_SGMII	(0x0 << ETH_MAC_GEN_CFG_XGMII_SGMII_SHIFT)
#define ETH_MAC_GEN_CFG_XGMII_SGMII_XAUI_RXAUI	(0x1 << ETH_MAC_GEN_CFG_XGMII_SGMII_SHIFT)
#define ETH_MAC_GEN_CFG_XGMII_SGMII_KR		(0x2 << ETH_MAC_GEN_CFG_XGMII_SGMII_SHIFT)

#define ETH_MAC_GEN_CFG_XAUI_RXAUI_SHIFT	3
#define ETH_MAC_GEN_CFG_XAUI_RXAUI_XAUI		(0 << ETH_MAC_GEN_CFG_XAUI_RXAUI_SHIFT)
#define ETH_MAC_GEN_CFG_XAUI_RXAUI_RXAUI	(1 << ETH_MAC_GEN_CFG_XAUI_RXAUI_SHIFT)

#define ETH_MAC_GEN_CFG_TBI_MSB_RX_SHIFT	5
#define ETH_MAC_GEN_CFG_TBI_MSB_RX_LSB		(0 << ETH_MAC_GEN_CFG_TBI_MSB_RX_SHIFT)
#define ETH_MAC_GEN_CFG_TBI_MSB_RX_MSB		(1 << ETH_MAC_GEN_CFG_TBI_MSB_RX_SHIFT)

#define ETH_MAC_GEN_CFG_SGMII_SEL_SHIFT		6
#define ETH_MAC_GEN_CFG_SGMII_SEL_10G_MAC	(0 << ETH_MAC_GEN_CFG_SGMII_SEL_SHIFT)
#define ETH_MAC_GEN_CFG_SGMII_SEL_1G_MAC	(1 << ETH_MAC_GEN_CFG_SGMII_SEL_SHIFT)

#define ETH_MAC_GEN_CFG_RGMII_SGMII_SEL_SHIFT	7
#define ETH_MAC_GEN_CFG_RGMII_SGMII_SEL_RGMII	(0 << ETH_MAC_GEN_CFG_RGMII_SGMII_SEL_SHIFT)
#define ETH_MAC_GEN_CFG_RGMII_SGMII_SEL_SGMII	(1 << ETH_MAC_GEN_CFG_RGMII_SGMII_SEL_SHIFT)

#define ETH_MAC_GEN_CFG_TBI_MSB_TX_SHIFT	9
#define ETH_MAC_GEN_CFG_TBI_MSB_TX_LSB		(0 << ETH_MAC_GEN_CFG_TBI_MSB_TX_SHIFT)
#define ETH_MAC_GEN_CFG_TBI_MSB_TX_MSB		(1 << ETH_MAC_GEN_CFG_TBI_MSB_TX_SHIFT)

#define ETH_MAC_GEN_CFG_MDIO_1_10_SHIFT		10
#define ETH_MAC_GEN_CFG_MDIO_1_10_1G_MAC	(0 << ETH_MAC_GEN_CFG_MDIO_1_10_SHIFT)
#define ETH_MAC_GEN_CFG_MDIO_1_10_10G_MAC	(1 << ETH_MAC_GEN_CFG_MDIO_1_10_SHIFT)

#define ETH_MAC_GEN_CFG_MDIO_POL_SHIFT		11
#define ETH_MAC_GEN_CFG_MDIO_POL_NORMAL		(0 << ETH_MAC_GEN_CFG_MDIO_POL_SHIFT)
#define ETH_MAC_GEN_CFG_MDIO_POL_FLIP		(1 << ETH_MAC_GEN_CFG_MDIO_POL_SHIFT)

#define ETH_MAC_GEN_CFG_SWAP_SERDES_RX(val)	\
	(ETH_MAC_GEN_CFG_SWAP_SERDES_RX_MASK & ((val) << ETH_MAC_GEN_CFG_SWAP_SERDES_RX_SHIFT))

#define ETH_MAC_GEN_CFG_SWAP_SERDES_TX(val)	\
	(ETH_MAC_GEN_CFG_SWAP_SERDES_TX_MASK & ((val) << ETH_MAC_GEN_CFG_SWAP_SERDES_TX_SHIFT))

/**** mac_1g_cfg register ****/

#define ETH_MAC_GEN_MAC_1G_CFG_SET_1000_SEL_SHIFT	0
#define ETH_MAC_GEN_MAC_1G_CFG_SET_1000_SEL_FROM_RGMII	(0 <<	\
							 ETH_MAC_GEN_MAC_1G_CFG_SET_1000_SEL_SHIFT)
#define ETH_MAC_GEN_MAC_1G_CFG_SET_1000_SEL_REG_DEF	(1 <<	\
							 ETH_MAC_GEN_MAC_1G_CFG_SET_1000_SEL_SHIFT)

#define ETH_MAC_GEN_MAC_1G_CFG_SET_1000_DEF_SHIFT	1
#define ETH_MAC_GEN_MAC_1G_CFG_SET_1000_DEF_0		(0 <<	\
							 ETH_MAC_GEN_MAC_1G_CFG_SET_1000_DEF_SHIFT)
#define ETH_MAC_GEN_MAC_1G_CFG_SET_1000_DEF_1		(1 <<	\
							 ETH_MAC_GEN_MAC_1G_CFG_SET_1000_DEF_SHIFT)

#define ETH_MAC_GEN_MAC_1G_CFG_SET_10_SEL_SHIFT		4
#define ETH_MAC_GEN_MAC_1G_CFG_SET_10_SEL_FROM_RGMII	(0 <<	\
							 ETH_MAC_GEN_MAC_1G_CFG_SET_10_SEL_SHIFT)
#define ETH_MAC_GEN_MAC_1G_CFG_SET_10_SEL_REG_DEF	(1 <<	\
							 ETH_MAC_GEN_MAC_1G_CFG_SET_10_SEL_SHIFT)

#define ETH_MAC_GEN_MAC_1G_CFG_SET_10_DEF_SHIFT		5
#define ETH_MAC_GEN_MAC_1G_CFG_SET_10_DEF_0		(0 <<	\
							 ETH_MAC_GEN_MAC_1G_CFG_SET_10_DEF_SHIFT)
#define ETH_MAC_GEN_MAC_1G_CFG_SET_10_DEF_1		(1 <<	\
							 ETH_MAC_GEN_MAC_1G_CFG_SET_10_DEF_SHIFT)

#define ETH_MAC_GEN_MAC_1G_CFG_SLEEPN_SHIFT		9
#define ETH_MAC_GEN_MAC_1G_CFG_SLEEPN_SLEEP		(0 << ETH_MAC_GEN_MAC_1G_CFG_SLEEPN_SHIFT)
#define ETH_MAC_GEN_MAC_1G_CFG_SLEEPN_NORMAL		(1 << ETH_MAC_GEN_MAC_1G_CFG_SLEEPN_SHIFT)

/**** mux_sel register ****/

#define ETH_MAC_GEN_MUX_SEL_SGMII_IN(serdes_num)	\
	(ETH_MAC_GEN_MUX_SEL_SGMII_IN_MASK & ((serdes_num) << ETH_MAC_GEN_MUX_SEL_SGMII_IN_SHIFT))

#define ETH_MAC_GEN_MUX_SEL_RXAUI_0_IN(serdes_num)	\
	(ETH_MAC_GEN_MUX_SEL_RXAUI_0_IN_MASK &		\
	 ((serdes_num) << ETH_MAC_GEN_MUX_SEL_RXAUI_0_IN_SHIFT))

#define ETH_MAC_GEN_MUX_SEL_RXAUI_1_IN(serdes_num)	\
	(ETH_MAC_GEN_MUX_SEL_RXAUI_1_IN_MASK &		\
	 ((serdes_num) << ETH_MAC_GEN_MUX_SEL_RXAUI_1_IN_SHIFT))

#define ETH_MAC_GEN_MUX_SEL_XAUI_0_IN(serdes_num)	\
	(ETH_MAC_GEN_MUX_SEL_XAUI_0_IN_MASK & ((serdes_num) << ETH_MAC_GEN_MUX_SEL_XAUI_0_IN_SHIFT))

#define ETH_MAC_GEN_MUX_SEL_XAUI_1_IN(serdes_num)	\
	(ETH_MAC_GEN_MUX_SEL_XAUI_1_IN_MASK & ((serdes_num) << ETH_MAC_GEN_MUX_SEL_XAUI_1_IN_SHIFT))

#define ETH_MAC_GEN_MUX_SEL_XAUI_2_IN(serdes_num)	\
	(ETH_MAC_GEN_MUX_SEL_XAUI_2_IN_MASK & ((serdes_num) << ETH_MAC_GEN_MUX_SEL_XAUI_2_IN_SHIFT))

#define ETH_MAC_GEN_MUX_SEL_XAUI_3_IN(serdes_num)	\
	(ETH_MAC_GEN_MUX_SEL_XAUI_3_IN_MASK & ((serdes_num) << ETH_MAC_GEN_MUX_SEL_XAUI_3_IN_SHIFT))

#define ETH_MAC_GEN_MUX_SEL_KR_IN(serdes_num)	\
	(ETH_MAC_GEN_MUX_SEL_KR_IN_MASK & ((serdes_num) << ETH_MAC_GEN_MUX_SEL_KR_IN_SHIFT))

#define ETH_MAC_GEN_MUX_SEL_SERDES_TX_XAUI_0	0x0
#define ETH_MAC_GEN_MUX_SEL_SERDES_TX_XAUI_1	0x1
#define ETH_MAC_GEN_MUX_SEL_SERDES_TX_XAUI_2	0x2
#define ETH_MAC_GEN_MUX_SEL_SERDES_TX_XAUI_3	0x3
#define ETH_MAC_GEN_MUX_SEL_SERDES_TX_RXAUI_0	0x4
#define ETH_MAC_GEN_MUX_SEL_SERDES_TX_RXAUI_1	0x5
#define ETH_MAC_GEN_MUX_SEL_SERDES_TX_SGMII	0x6
#define ETH_MAC_GEN_MUX_SEL_SERDES_TX_KR	0x7

#define ETH_MAC_GEN_MUX_SEL_SERDES_0_TX(in_sel)	\
	(ETH_MAC_GEN_MUX_SEL_SERDES_0_TX_MASK & ((in_sel) << ETH_MAC_GEN_MUX_SEL_SERDES_0_TX_SHIFT))
#define ETH_MAC_GEN_MUX_SEL_SERDES_1_TX(in_sel)	\
	(ETH_MAC_GEN_MUX_SEL_SERDES_1_TX_MASK & ((in_sel) << ETH_MAC_GEN_MUX_SEL_SERDES_1_TX_SHIFT))
#define ETH_MAC_GEN_MUX_SEL_SERDES_2_TX(in_sel)	\
	(ETH_MAC_GEN_MUX_SEL_SERDES_2_TX_MASK & ((in_sel) << ETH_MAC_GEN_MUX_SEL_SERDES_2_TX_SHIFT))
#define ETH_MAC_GEN_MUX_SEL_SERDES_3_TX(in_sel)	\
	(ETH_MAC_GEN_MUX_SEL_SERDES_3_TX_MASK & ((in_sel) << ETH_MAC_GEN_MUX_SEL_SERDES_3_TX_SHIFT))

#endif /* __AL_HAL_ETH_MAC_CONFIG_DEFS_H__ */
