/*
 * Copyright 2017, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */
#include "al_hal_iofic.h"
#include "al_hal_iofic_regs.h"
#include "al_hal_pmdt_iofic.h"

#define AL_PMDT_INT_GROUP_A_SUM \
	(AL_PMDT_INT_GROUP_A_PMU_ADAPT_SSMAE_0 | \
	AL_PMDT_INT_GROUP_A_PMU_ADAPT_SSMAE_1 | \
	AL_PMDT_INT_GROUP_A_ELA_0_ADAPT_SSMAE_0 | \
	AL_PMDT_INT_GROUP_A_ELA_0_ADAPT_SSMAE_1 | \
	AL_PMDT_INT_GROUP_A_PMU_UDMA_0_SSMAE_0 | \
	AL_PMDT_INT_GROUP_A_PMU_UDMA_1_SSMAE_0 | \
	AL_PMDT_INT_GROUP_A_PMU_UDMA_2_SSMAE_0 | \
	AL_PMDT_INT_GROUP_A_PMU_UDMA_3_SSMAE_0 | \
	AL_PMDT_INT_GROUP_A_PMU_UDMA_0_SSMAE_1 | \
	AL_PMDT_INT_GROUP_A_PMU_UDMA_1_SSMAE_1 | \
	AL_PMDT_INT_GROUP_A_PMU_UDMA_2_SSMAE_1 | \
	AL_PMDT_INT_GROUP_A_PMU_UDMA_3_SSMAE_1 | \
	AL_PMDT_INT_GROUP_A_ELA_UDMA_0_SSMA_0 | \
	AL_PMDT_INT_GROUP_A_ELA_UDMA_1_SSMA_0 | \
	AL_PMDT_INT_GROUP_A_ELA_UDMA_2_SSMA_0 | \
	AL_PMDT_INT_GROUP_A_ELA_UDMA_3_SSMA_0 | \
	AL_PMDT_INT_GROUP_A_ELA_UDMA_0_SSMA_1 | \
	AL_PMDT_INT_GROUP_A_ELA_UDMA_1_SSMA_1 | \
	AL_PMDT_INT_GROUP_A_ELA_UDMA_2_SSMA_1 | \
	AL_PMDT_INT_GROUP_A_ELA_UDMA_3_SSMA_1 | \
	AL_PMDT_INT_GROUP_A_PMU_ADAPT_ETH_10_0 | \
	AL_PMDT_INT_GROUP_A_ELA_0_ADAPT_OR_ELA_1_ADPT_ETH_10_0 | \
	AL_PMDT_INT_GROUP_A_PMU_ADAPT_ETH_10_1 | \
	AL_PMDT_INT_GROUP_A_PMU_EC_0_ETH_100_0 | \
	AL_PMDT_INT_GROUP_A_PMU_NBC | \
	AL_PMDT_INT_GROUP_A_ELA_EC_0_ETH_100_0 | \
	AL_PMDT_INT_GROUP_A_PMU_EC_1_ETH_100_0 | \
	AL_PMDT_INT_GROUP_A_ELA_EC_1_ETH_100_0 | \
	AL_PMDT_INT_GROUP_A_PMU_DDR_CONTROLER_0 | \
	AL_PMDT_INT_GROUP_A_PMU_DDR_CONTROLER_1 | \
	AL_PMDT_INT_GROUP_A_ELA_DDR_CONTROLER_0 | \
	AL_PMDT_INT_GROUP_A_ELA_DDR_CONTROLER_1)

#define AL_PMDT_INT_GROUP_B_SUM \
	(AL_PMDT_INT_GROUP_B_PMU_ADAPT_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_PMU_ADAPT_ETH_100_1 | \
	AL_PMDT_INT_GROUP_B_PMU_ADAPT_ETH_100_2 | \
	AL_PMDT_INT_GROUP_B_PMU_ADAPT_ETH_100_3 | \
	AL_PMDT_INT_GROUP_B_ELA_0_ADAPT_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_ELA_0_ADAPT_ETH_100_1 | \
	AL_PMDT_INT_GROUP_B_ELA_0_ADAPT_ETH_100_2 | \
	AL_PMDT_INT_GROUP_B_ELA_0_ADAPT_ETH_100_3 | \
	AL_PMDT_INT_GROUP_B_PMU_UDMA_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_PMU_UDMA_ETH_100_1 | \
	AL_PMDT_INT_GROUP_B_PMU_UDMA_ETH_100_2 | \
	AL_PMDT_INT_GROUP_B_PMU_UDMA_ETH_100_3 | \
	AL_PMDT_INT_GROUP_B_ELA_UDMA_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_ELA_UDMA_ETH_100_1 | \
	AL_PMDT_INT_GROUP_B_ELA_UDMA_ETH_100_2 | \
	AL_PMDT_INT_GROUP_B_ELA_UDMA_ETH_100_3 | \
	AL_PMDT_INT_GROUP_B_PMU_EC_2_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_ELA_EC_2_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_PMU_SHARED_RESOURCE_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_ELA_SHARED_RESOURCE_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_PMU_SHARED_CACHE_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_ELA_SHARED_CACHE_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_PMU_EC_3_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_ELA_EC_3_ETH_100_0 | \
	AL_PMDT_INT_GROUP_B_PMU_CPU_CLUSTER_0 | \
	AL_PMDT_INT_GROUP_B_PMU_CPU_CLUSTER_1 | \
	AL_PMDT_INT_GROUP_B_PMU_CPU_CLUSTER_2 | \
	AL_PMDT_INT_GROUP_B_PMU_CPU_CLUSTER_3 | \
	AL_PMDT_INT_GROUP_B_ELA_CPU_CLUSTER_0 | \
	AL_PMDT_INT_GROUP_B_ELA_CPU_CLUSTER_1 | \
	AL_PMDT_INT_GROUP_B_ELA_CPU_CLUSTER_2 | \
	AL_PMDT_INT_GROUP_B_ELA_CPU_CLUSTER_3)

#define AL_PMDT_INT_GROUP_C_SUM \
	(AL_PMDT_INT_GROUP_C_PMU_ADAPT_SATA_0 | \
	AL_PMDT_INT_GROUP_C_PMU_ADAPT_SATA_1 | \
	AL_PMDT_INT_GROUP_C_ELA_0_ADAPT_SATA_0 | \
	AL_PMDT_INT_GROUP_C_ELA_ADAPT_SATA_1 | \
	AL_PMDT_INT_GROUP_C_PMU_ADAPT_SATA_2 | \
	AL_PMDT_INT_GROUP_C_PMU_ADAPT_SATA_3 | \
	AL_PMDT_INT_GROUP_C_ELA_ADAPT_SATA_2 | \
	AL_PMDT_INT_GROUP_C_ELA_ADAPT_SATA_3 | \
	AL_PMDT_INT_GROUP_C_PMU_ADAPT_SATA_4 | \
	AL_PMDT_INT_GROUP_C_PMU_ADAPT_SATA_5 | \
	AL_PMDT_INT_GROUP_C_ELA_ADAPT_SATA_4 | \
	AL_PMDT_INT_GROUP_C_ELA_ADAPT_SATA_5 | \
	AL_PMDT_INT_GROUP_C_PMU_ADAPT_SATA_6 | \
	AL_PMDT_INT_GROUP_C_PMU_ADAPT_SATA_7 | \
	AL_PMDT_INT_GROUP_C_ELA_ADAPT_SATA_6 | \
	AL_PMDT_INT_GROUP_C_ELA_ADAPT_SATA_7 | \
	AL_PMDT_INT_GROUP_C_PMU_PCIECORE_0 | \
	AL_PMDT_INT_GROUP_C_PMU_PCIECORE_1 | \
	AL_PMDT_INT_GROUP_C_PMU_PCIECORE_2 | \
	AL_PMDT_INT_GROUP_C_PMU_PCIECORE_3 | \
	AL_PMDT_INT_GROUP_C_PMU_PCIECORE_4 | \
	AL_PMDT_INT_GROUP_C_PMU_PCIECORE_5 | \
	AL_PMDT_INT_GROUP_C_PMU_PCIECORE_6 | \
	AL_PMDT_INT_GROUP_C_PMU_PCIECORE_7 | \
	AL_PMDT_INT_GROUP_C_ELA_PCIECORE_0 | \
	AL_PMDT_INT_GROUP_C_ELA_PCIECORE_1 | \
	AL_PMDT_INT_GROUP_C_ELA_PCIECORE_2 | \
	AL_PMDT_INT_GROUP_C_ELA_PCIECORE_3 | \
	AL_PMDT_INT_GROUP_C_ELA_PCIECORE_4 | \
	AL_PMDT_INT_GROUP_C_ELA_PCIECORE_5 | \
	AL_PMDT_INT_GROUP_C_ELA_PCIECORE_6 | \
	AL_PMDT_INT_GROUP_C_ELA_PCIECORE_7)

#define AL_PMDT_INT_GROUP_D_SUM \
	(AL_PMDT_INT_GROUP_D_PMU_PCIE_SLVAXI_0 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_SLVAXI_1 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_SLVAXI_2 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_SLVAXI_3 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_SLVAXI_4 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_SLVAXI_5 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_SLVAXI_6 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_SLVAXI_7 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_SLVAXI_0 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_SLVAXI_1 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_SLVAXI_2 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_SLVAXI_3 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_SLVAXI_4 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_SLVAXI_5 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_SLVAXI_6 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_SLVAXI_7 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_MSTRAXI_0 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_MSTRAXI_1 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_MSTRAXI_2 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_MSTRAXI_3 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_MSTRAXI_4 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_MSTRAXI_5 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_MSTRAXI_6 | \
	AL_PMDT_INT_GROUP_D_PMU_PCIE_MSTRAXI_7 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_MSTRAXI_0 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_MSTRAXI_1 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_MSTRAXI_2 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_MSTRAXI_3 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_MSTRAXI_4 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_MSTRAXI_5 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_MSTRAXI_6 | \
	AL_PMDT_INT_GROUP_D_ELA_PCIE_MSTRAXI_7)

void al_pmdt_iofic_error_masks_get(void *handle,
		uint32_t *a, uint32_t *b, uint32_t *c, uint32_t *d)
{
	/** handle is a place holder for future possible API change */
	(void *)handle;
	al_assert(a);
	al_assert(b);
	al_assert(c);
	al_assert(d);

	*a = AL_PMDT_INT_GROUP_A_SUM;
	*b = AL_PMDT_INT_GROUP_B_SUM;
	*c = AL_PMDT_INT_GROUP_C_SUM;
	*d = AL_PMDT_INT_GROUP_D_SUM;
}

void al_pmdt_iofic_error_ints_unmask(void *handle)
{
	void __iomem *ints_base = handle;

	uint32_t a, b, c, d;

	al_pmdt_iofic_error_masks_get(handle, &a, &b, &c, &d);

		/* EC IOFIC config */
	al_iofic_config(ints_base,
			AL_INT_GROUP_A,
			INT_CONTROL_GRP_MASK_MSI_X);
	al_iofic_config(ints_base,
			AL_INT_GROUP_B,
			INT_CONTROL_GRP_MASK_MSI_X);
	al_iofic_config(ints_base,
			AL_INT_GROUP_C,
			INT_CONTROL_GRP_MASK_MSI_X);
	al_iofic_config(ints_base,
			AL_INT_GROUP_D,
			INT_CONTROL_GRP_MASK_MSI_X);

	al_iofic_clear_cause(ints_base,
			AL_INT_GROUP_A,
			a);
	al_iofic_clear_cause(ints_base,
			AL_INT_GROUP_B,
			b);
	al_iofic_clear_cause(ints_base,
			AL_INT_GROUP_C,
			c);
	al_iofic_clear_cause(ints_base,
			AL_INT_GROUP_D,
			d);

	al_iofic_unmask(ints_base,
		AL_INT_GROUP_A,
		a);
	al_iofic_unmask(ints_base,
		AL_INT_GROUP_B,
		b);
	al_iofic_unmask(ints_base,
		AL_INT_GROUP_C,
		c);
	al_iofic_unmask(ints_base,
		AL_INT_GROUP_D,
		d);
}
