
#
# Makefile RTL83xx ASIC driver
#

EXTRA_CFLAGS    += -I ./drivers/net/phy/rtl83xx_api -D MDC_MDIO_OPERATION

obj-$(CONFIG_RTL83XX_API) += acl.o
obj-$(CONFIG_RTL83XX_API) += cpu.o
obj-$(CONFIG_RTL83XX_API) += dot1x.o
obj-$(CONFIG_RTL83XX_API) += eee.o
obj-$(CONFIG_RTL83XX_API) += i2c.o
obj-$(CONFIG_RTL83XX_API) += igmp.o
obj-$(CONFIG_RTL83XX_API) += interrupt.o
obj-$(CONFIG_RTL83XX_API) += l2.o
obj-$(CONFIG_RTL83XX_API) += leaky.o
obj-$(CONFIG_RTL83XX_API) += led.o
obj-$(CONFIG_RTL83XX_API) += mirror.o
obj-$(CONFIG_RTL83XX_API) += oam.o
obj-$(CONFIG_RTL83XX_API) += port.o
obj-$(CONFIG_RTL83XX_API) += ptp.o
obj-$(CONFIG_RTL83XX_API) += qos.o
obj-$(CONFIG_RTL83XX_API) += rate.o
obj-$(CONFIG_RTL83XX_API) += rldp.o
obj-$(CONFIG_RTL83XX_API) += rtk_switch.o
obj-$(CONFIG_RTL83XX_API) += smi.o
obj-$(CONFIG_RTL83XX_API) += stat.o
obj-$(CONFIG_RTL83XX_API) += storm.o
obj-$(CONFIG_RTL83XX_API) += svlan.o
obj-$(CONFIG_RTL83XX_API) += trap.o
obj-$(CONFIG_RTL83XX_API) += trunk.o
obj-$(CONFIG_RTL83XX_API) += vlan.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_acl.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_cputag.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_dot1x.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_eav.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_eee.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_fc.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_green.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_hsb.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_i2c.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_igmp.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_inbwctrl.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_interrupt.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_led.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_lut.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_meter.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_mib.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_mirror.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_misc.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_oam.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_phy.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_port.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_portIsolation.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_qos.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_rldp.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_rma.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_scheduling.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_storm.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_svlan.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_trunking.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_unknownMulticast.o
obj-$(CONFIG_RTL83XX_API) += rtl8367c_asicdrv_vlan.o
