/*
 * Copyright 2017, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

#ifndef	__AL_OTP_STORAGE_LAYOUT_V2_H__
#define	__AL_OTP_STORAGE_LAYOUT_V2_H__

#define	OTP_FIELD_WORD_OFFSET_DEVICE_SER_NUM		0
#define	OTP_FIELD_WORD_SIZE_DEVICE_SER_NUM		2

#define	OTP_FIELD_WORD_OFFSET_MINIMAL_SW_VER		2
#define	OTP_FIELD_WORD_SIZE_MINIMAL_SW_VER		1

#define	OTP_FIELD_WORD_OFFSET_PUK0_MOD_HASH		3
#define	OTP_FIELD_WORD_SIZE_PUK0_MOD_HASH		8

#define	OTP_FIELD_WORD_OFFSET_FREE			11
#define	OTP_FIELD_WORD_SIZE_FREE			18

#define	OTP_FIELD_WORD_OFFSET_HW_INITIATED_MEM_REPAIR	29
#define	OTP_FIELD_BIT_OFFSET_HW_INITIATED_MEM_REPAIR	0
#define	OTP_FIELD_BIT_MASK_SET_HW_INITIATED_MEM_REPAIR	0x00000001

#define	OTP_FIELD_WORD_OFFSET_RSRVD1			29
#define	OTP_FIELD_BIT_OFFSET_RSRVD1			1
#define	OTP_FIELD_BIT_MASK_SET_RSRVD1			0xfffffffe

#define	OTP_FIELD_WORD_OFFSET_DIRECT_BOOT_DIS		30
#define	OTP_FIELD_BIT_OFFSET_DIRECT_BOOT_DIS		0
#define	OTP_FIELD_BIT_MASK_SET_DIRECT_BOOT_DIS		0x00000001

#define	OTP_FIELD_WORD_OFFSET_PRELOAD_DISABLE		30
#define	OTP_FIELD_BIT_OFFSET_PRELOAD_DISABLE		1
#define	OTP_FIELD_BIT_MASK_SET_PRELOAD_DISABLE		0x00000002

#define	OTP_FIELD_WORD_OFFSET_SPI_DBG_DISABLE		30
#define	OTP_FIELD_BIT_OFFSET_SPI_DBG_DISABLE		2
#define	OTP_FIELD_BIT_MASK_SET_SPI_DBG_DISABLE		0x00000004

#define	OTP_FIELD_WORD_OFFSET_JTAG_DBG_DISABLE		30
#define	OTP_FIELD_BIT_OFFSET_JTAG_DBG_DISABLE		3
#define	OTP_FIELD_BIT_MASK_SET_JTAG_DBG_DISABLE		0x00000008

#define	OTP_FIELD_WORD_OFFSET_SECURE_BOOT_EN		30
#define	OTP_FIELD_BIT_OFFSET_SECURE_BOOT_EN		4
#define	OTP_FIELD_BIT_MASK_SET_SECURE_BOOT_EN		0x00000010

#define	OTP_FIELD_WORD_OFFSET_ROM_DBG_DIS		30
#define	OTP_FIELD_BIT_OFFSET_ROM_DBG_DIS		5
#define	OTP_FIELD_BIT_MASK_SET_ROM_DBG_DIS		0x00000020

#define	OTP_FIELD_WORD_OFFSET_SNOR_SECURE_BOOT_DIS	30
#define	OTP_FIELD_BIT_OFFSET_SNOR_SECURE_BOOT_DIS	6
#define	OTP_FIELD_BIT_MASK_SET_SNOR_SECURE_BOOT_DIS	0x00000040

#define	OTP_FIELD_WORD_OFFSET_RSRVD2			30
#define	OTP_FIELD_BIT_OFFSET_RSRVD2			7
#define	OTP_FIELD_BIT_MASK_SET_RSRVD2			0x00000080

#define	OTP_FIELD_WORD_OFFSET_NAND_SECURE_BOOT_DIS	30
#define	OTP_FIELD_BIT_OFFSET_NAND_SECURE_BOOT_DIS	8
#define	OTP_FIELD_BIT_MASK_SET_NAND_SECURE_BOOT_DIS	0x00000100

#define	OTP_FIELD_WORD_OFFSET_UART_SECURE_BOOT_DIS	30
#define	OTP_FIELD_BIT_OFFSET_UART_SECURE_BOOT_DIS	9
#define	OTP_FIELD_BIT_MASK_SET_UART_SECURE_BOOT_DIS	0x00000200

#define	OTP_FIELD_WORD_OFFSET_RSRVD3			30
#define	OTP_FIELD_BIT_OFFSET_RSRVD3			10
#define	OTP_FIELD_BIT_MASK_SET_RSRVD3			0xfffffc00

#define	OTP_FIELD_WORD_OFFSET_LOCKS			31
#define	OTP_FIELD_WORD_SIZE_LOCKS			1

#endif

