/*
 * Copyright 2017, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

#ifndef __AL_OTP_STORAGE_LAYOUT_H__
#define __AL_OTP_STORAGE_LAYOUT_H__

#include "al_hal_plat_types.h"

/** Layout */
struct al_otp_storage_layout {
	uint8_t		WORD_OFFSET_DEVICE_SER_NUM;
	uint8_t		WORD_SIZE_DEVICE_SER_NUM;
	uint8_t		WORD_OFFSET_MINIMAL_SW_VER;
	uint8_t		WORD_SIZE_MINIMAL_SW_VER;
	uint8_t		WORD_OFFSET_PUK0_MOD_HASH;
	uint8_t		WORD_SIZE_PUK0_MOD_HASH;
	uint8_t		WORD_OFFSET_PUK1_MOD_HASH;
	uint8_t		WORD_SIZE_PUK1_MOD_HASH;
	uint8_t		WORD_OFFSET_PUK2_MOD_HASH;
	uint8_t		WORD_SIZE_PUK2_MOD_HASH;
	uint8_t		WORD_OFFSET_PUK_IDX;
	uint8_t		BIT_OFFSET_PUK_IDX;
	uint8_t		WORD_OFFSET_EFUSE_PLD;
	uint8_t		WORD_SIZE_EFUSE_PLD;
	uint8_t		WORD_OFFSET_PUK3_MOD_HASH;
	uint8_t		WORD_SIZE_PUK3_MOD_HASH;
	uint8_t		WORD_OFFSET_HW_INITIATED_MEM_REPAIR;
	uint8_t		BIT_OFFSET_HW_INITIATED_MEM_REPAIR;
	uint8_t		WORD_OFFSET_SW_INITIATED_MEM_REPAIR;
	uint8_t		BIT_OFFSET_SW_INITIATED_MEM_REPAIR;
	uint8_t		WORD_OFFSET_DIRECT_BOOT_DIS;
	uint8_t		BIT_OFFSET_DIRECT_BOOT_DIS;
	uint8_t		WORD_OFFSET_PRELOAD_DISABLE;
	uint8_t		BIT_OFFSET_PRELOAD_DISABLE;
	uint8_t		WORD_OFFSET_SPI_DBG_DISABLE;
	uint8_t		BIT_OFFSET_SPI_DBG_DISABLE;
	uint8_t		WORD_OFFSET_JTAG_DBG_DISABLE;
	uint8_t		BIT_OFFSET_JTAG_DBG_DISABLE;
	uint8_t		WORD_OFFSET_SECURE_BOOT_EN;
	uint8_t		BIT_OFFSET_SECURE_BOOT_EN;
	uint8_t		WORD_OFFSET_ROM_DBG_DIS;
	uint8_t		BIT_OFFSET_ROM_DBG_DIS;
	uint8_t		WORD_OFFSET_SNOR_SECURE_BOOT_DIS;
	uint8_t		BIT_OFFSET_SNOR_SECURE_BOOT_DIS;
	uint8_t		WORD_OFFSET_NAND_SECURE_BOOT_DIS;
	uint8_t		BIT_OFFSET_NAND_SECURE_BOOT_DIS;
	uint8_t		WORD_OFFSET_UART_SECURE_BOOT_DIS;
	uint8_t		BIT_OFFSET_UART_SECURE_BOOT_DIS;
	uint8_t		WORD_OFFSET_UART_CLI_SECURE_BOOT_DIS;
	uint8_t		BIT_OFFSET_UART_CLI_SECURE_BOOT_DIS;
	uint8_t		WORD_OFFSET_TZ_EN;
	uint8_t		BIT_OFFSET_TZ_EN;
	uint8_t		WORD_OFFSET_JTAG_SOC_DISABLE;
	uint8_t		BIT_OFFSET_JTAG_SOC_DISABLE;
	uint8_t		WORD_OFFSET_SPI_DBG_PASW_EN;
	uint8_t		BIT_OFFSET_SPI_DBG_PASW_EN;
	uint8_t		WORD_OFFSET_OTPR_OVERRIDE_BY_PLD_DIS;
	uint8_t		BIT_OFFSET_OTPR_OVERRIDE_BY_PLD_DIS;
	uint8_t		WORD_OFFSET_CPU_DBG_AND_TRACE_DIS;
	uint8_t		BIT_OFFSET_CPU_DBG_AND_TRACE_DIS;
	uint8_t		WORD_OFFSET_SECURE_DBG_AND_TRACE_DIS;
	uint8_t		BIT_OFFSET_SECURE_DBG_AND_TRACE_DIS;
	uint8_t		WORD_OFFSET_DBG_EN;
	uint8_t		BIT_OFFSET_DBG_EN;
	uint8_t		WORD_OFFSET_CHIP_REVISION_ID;
	uint8_t		BIT_OFFSET_CHIP_REVISION_ID;
	unsigned int	BIT_MASK_SET_PUK_IDX;
	unsigned int	BIT_MASK_SET_HW_INITIATED_MEM_REPAIR;
	unsigned int	BIT_MASK_SET_SW_INITIATED_MEM_REPAIR;
	unsigned int	BIT_MASK_SET_DIRECT_BOOT_DIS;
	unsigned int	BIT_MASK_SET_PRELOAD_DISABLE;
	unsigned int	BIT_MASK_SET_SPI_DBG_DISABLE;
	unsigned int	BIT_MASK_SET_JTAG_DBG_DISABLE;
	unsigned int	BIT_MASK_SET_SECURE_BOOT_EN;
	unsigned int	BIT_MASK_SET_ROM_DBG_DIS;
	unsigned int	BIT_MASK_SET_SNOR_SECURE_BOOT_DIS;
	unsigned int	BIT_MASK_SET_NAND_SECURE_BOOT_DIS;
	unsigned int	BIT_MASK_SET_UART_SECURE_BOOT_DIS;
	unsigned int	BIT_MASK_SET_UART_CLI_SECURE_BOOT_DIS;
	unsigned int	BIT_MASK_SET_TZ_EN;
	unsigned int	BIT_MASK_SET_JTAG_SOC_DISABLE;
	unsigned int	BIT_MASK_SET_SPI_DBG_PASW_EN;
	unsigned int	BIT_MASK_SET_OTPR_OVERRIDE_BY_PLD_DIS;
	unsigned int	BIT_MASK_SET_CPU_DBG_AND_TRACE_DIS;
	unsigned int	BIT_MASK_SET_SECURE_DBG_AND_TRACE_DIS;
	unsigned int	BIT_MASK_SET_DBG_EN;
	unsigned int	BIT_MASK_SET_CHIP_REVISION_ID;
};

#endif

