/*
 * Copyright 2017, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

#ifndef	__AL_OTP_STORAGE_LAYOUT_V3_H__
#define	__AL_OTP_STORAGE_LAYOUT_V3_H__

#define	OTP_FIELD_WORD_OFFSET_DEVICE_SER_NUM		0
#define	OTP_FIELD_WORD_SIZE_DEVICE_SER_NUM		2

#define	OTP_FIELD_WORD_OFFSET_MINIMAL_SW_VER		2
#define	OTP_FIELD_WORD_SIZE_MINIMAL_SW_VER		1

#define	OTP_FIELD_WORD_OFFSET_PUK0_MOD_HASH		3
#define	OTP_FIELD_WORD_SIZE_PUK0_MOD_HASH		8

#define	OTP_FIELD_WORD_OFFSET_PUK1_MOD_HASH		11
#define	OTP_FIELD_WORD_SIZE_PUK1_MOD_HASH		8

#define	OTP_FIELD_WORD_OFFSET_PUK2_MOD_HASH		19
#define	OTP_FIELD_WORD_SIZE_PUK2_MOD_HASH		8

#define	OTP_FIELD_WORD_OFFSET_PUK_IDX			27
#define	OTP_FIELD_BIT_OFFSET_PUK_IDX			0
#define	OTP_FIELD_BIT_MASK_SET_PUK_IDX			0x00000007

#define	OTP_FIELD_WORD_OFFSET_RSRVD0			27
#define	OTP_FIELD_BIT_OFFSET_RSRVD0			3
#define	OTP_FIELD_BIT_MASK_SET_RSRVD0			0xfffffff8

#define	OTP_FIELD_WORD_OFFSET_RSRVD1			28
#define	OTP_FIELD_WORD_SIZE_RSRVD1			4

#define	OTP_FIELD_WORD_OFFSET_EFUSE_PLD			32
#define	OTP_FIELD_WORD_SIZE_EFUSE_PLD			76

#define	OTP_FIELD_WORD_OFFSET_PUK3_MOD_HASH		108
#define	OTP_FIELD_WORD_SIZE_PUK3_MOD_HASH		8

#define	OTP_FIELD_WORD_OFFSET_HW_INITIATED_MEM_REPAIR	116
#define	OTP_FIELD_BIT_OFFSET_HW_INITIATED_MEM_REPAIR	0
#define	OTP_FIELD_BIT_MASK_SET_HW_INITIATED_MEM_REPAIR	0x00000001

#define	OTP_FIELD_WORD_OFFSET_RSRVD2			116
#define	OTP_FIELD_BIT_OFFSET_RSRVD2			1
#define	OTP_FIELD_BIT_MASK_SET_RSRVD2			0x0000001e

#define	OTP_FIELD_WORD_OFFSET_SW_INITIATED_MEM_REPAIR	116
#define	OTP_FIELD_BIT_OFFSET_SW_INITIATED_MEM_REPAIR	5
#define	OTP_FIELD_BIT_MASK_SET_SW_INITIATED_MEM_REPAIR	0x00000020

#define	OTP_FIELD_WORD_OFFSET_RSRVD3			116
#define	OTP_FIELD_BIT_OFFSET_RSRVD3			6
#define	OTP_FIELD_BIT_MASK_SET_RSRVD3			0x3ffffc00

#define	OTP_FIELD_WORD_OFFSET_CHIP_REV_ID		116
#define	OTP_FIELD_BIT_OFFSET_CHIP_REV_ID		30
#define	OTP_FIELD_BIT_MASK_SET_CHIP_REV_ID		0xc0000000

#define	OTP_FIELD_WORD_OFFSET_RSRVD4			117
#define	OTP_FIELD_WORD_SIZE_RSRVD4			3

#define	OTP_FIELD_WORD_OFFSET_DIRECT_BOOT_DIS		120
#define	OTP_FIELD_BIT_OFFSET_DIRECT_BOOT_DIS		0
#define	OTP_FIELD_BIT_MASK_SET_DIRECT_BOOT_DIS		0x00000001

#define	OTP_FIELD_WORD_OFFSET_PRELOAD_DISABLE		120
#define	OTP_FIELD_BIT_OFFSET_PRELOAD_DISABLE		1
#define	OTP_FIELD_BIT_MASK_SET_PRELOAD_DISABLE		0x00000002

#define	OTP_FIELD_WORD_OFFSET_SPI_DBG_DISABLE		120
#define	OTP_FIELD_BIT_OFFSET_SPI_DBG_DISABLE		2
#define	OTP_FIELD_BIT_MASK_SET_SPI_DBG_DISABLE		0x00000004

#define	OTP_FIELD_WORD_OFFSET_JTAG_DBG_DISABLE		120
#define	OTP_FIELD_BIT_OFFSET_JTAG_DBG_DISABLE		3
#define	OTP_FIELD_BIT_MASK_SET_JTAG_DBG_DISABLE		0x00000008

#define	OTP_FIELD_WORD_OFFSET_SECURE_BOOT_EN		120
#define	OTP_FIELD_BIT_OFFSET_SECURE_BOOT_EN		4
#define	OTP_FIELD_BIT_MASK_SET_SECURE_BOOT_EN		0x00000010

#define	OTP_FIELD_WORD_OFFSET_ROM_DBG_DIS		120
#define	OTP_FIELD_BIT_OFFSET_ROM_DBG_DIS		5
#define	OTP_FIELD_BIT_MASK_SET_ROM_DBG_DIS		0x00000020

#define	OTP_FIELD_WORD_OFFSET_SNOR_SECURE_BOOT_DIS	120
#define	OTP_FIELD_BIT_OFFSET_SNOR_SECURE_BOOT_DIS	6
#define	OTP_FIELD_BIT_MASK_SET_SNOR_SECURE_BOOT_DIS	0x00000040

#define	OTP_FIELD_WORD_OFFSET_RSRVD5			120
#define	OTP_FIELD_BIT_OFFSET_RSRVD5			7
#define	OTP_FIELD_BIT_MASK_SET_RSRVD5			0x00000080

#define	OTP_FIELD_WORD_OFFSET_NAND_SECURE_BOOT_DIS	120
#define	OTP_FIELD_BIT_OFFSET_NAND_SECURE_BOOT_DIS	8
#define	OTP_FIELD_BIT_MASK_SET_NAND_SECURE_BOOT_DIS	0x00000100

#define	OTP_FIELD_WORD_OFFSET_UART_SECURE_BOOT_DIS	120
#define	OTP_FIELD_BIT_OFFSET_UART_SECURE_BOOT_DIS	9
#define	OTP_FIELD_BIT_MASK_SET_UART_SECURE_BOOT_DIS	0x00000200

#define	OTP_FIELD_WORD_OFFSET_UART_CLI_SECURE_BOOT_DIS	120
#define	OTP_FIELD_BIT_OFFSET_UART_CLI_SECURE_BOOT_DIS	10
#define	OTP_FIELD_BIT_MASK_SET_UART_CLI_SECURE_BOOT_DIS	0x00000400

#define	OTP_FIELD_WORD_OFFSET_TZ_EN			120
#define	OTP_FIELD_BIT_OFFSET_TZ_EN			11
#define	OTP_FIELD_BIT_MASK_SET_TZ_EN			0x00000800

#define	OTP_FIELD_WORD_OFFSET_JTAG_SOC_DISABLE		120
#define	OTP_FIELD_BIT_OFFSET_JTAG_SOC_DISABLE		12
#define	OTP_FIELD_BIT_MASK_SET_JTAG_SOC_DISABLE		0x00001000

#define	OTP_FIELD_WORD_OFFSET_SPI_DBG_PASW_EN		120
#define	OTP_FIELD_BIT_OFFSET_SPI_DBG_PASW_EN		13
#define	OTP_FIELD_BIT_MASK_SET_SPI_DBG_PASW_EN		0x00002000

#define	OTP_FIELD_WORD_OFFSET_OTPR_OVERRIDE_BY_PLD_DIS	120
#define	OTP_FIELD_BIT_OFFSET_OTPR_OVERRIDE_BY_PLD_DIS	14
#define	OTP_FIELD_BIT_MASK_SET_OTPR_OVERRIDE_BY_PLD_DIS	0x00004000

#define	OTP_FIELD_WORD_OFFSET_CPU_DBG_AND_TRACE_DIS	120
#define	OTP_FIELD_BIT_OFFSET_CPU_DBG_AND_TRACE_DIS	15
#define	OTP_FIELD_BIT_MASK_SET_CPU_DBG_AND_TRACE_DIS	0x00008000

#define	OTP_FIELD_WORD_OFFSET_SECURE_DBG_AND_TRACE_DIS	120
#define	OTP_FIELD_BIT_OFFSET_SECURE_DBG_AND_TRACE_DIS	16
#define	OTP_FIELD_BIT_MASK_SET_SECURE_DBG_AND_TRACE_DIS	0x00010000

#define	OTP_FIELD_WORD_OFFSET_RSRVD6			120
#define	OTP_FIELD_BIT_OFFSET_RSRVD6			17
#define	OTP_FIELD_BIT_MASK_SET_RSRVD6			0xfffe0000

#define	OTP_FIELD_WORD_OFFSET_DBG_EN			121
#define	OTP_FIELD_BIT_OFFSET_DBG_EN			0
#define	OTP_FIELD_BIT_MASK_SET_DBG_EN			0x00000003

#define	OTP_FIELD_WORD_OFFSET_RSRVD7			121
#define	OTP_FIELD_BIT_OFFSET_RSRVD7			2
#define	OTP_FIELD_BIT_MASK_SET_RSRVD7			0xfffffffc

#define	OTP_FIELD_WORD_OFFSET_RSRVD8			122
#define	OTP_FIELD_WORD_SIZE_RSRVD8			2

#define	OTP_FIELD_WORD_OFFSET_LOCKS			124
#define	OTP_FIELD_WORD_SIZE_LOCKS			4

#endif
