include $(srctree)/drivers/soc/alpine/alpine_hal.mk

obj-$(CONFIG_AL_DMA) += al_dma.o
obj-$(CONFIG_AL_DMA) += al_dma_core.o
obj-$(CONFIG_AL_DMA) += al_dma_cleanup.o
obj-$(CONFIG_AL_DMA) += al_dma_sysfs.o
obj-$(CONFIG_AL_DMA) += al_dma_prep_interrupt.o
obj-$(CONFIG_AL_DMA) += al_dma_prep_memcpy.o
obj-$(CONFIG_AL_DMA) += al_dma_prep_memset.o
obj-$(CONFIG_AL_DMA) += al_dma_prep_xor.o
obj-$(CONFIG_AL_DMA) += al_dma_prep_xor_val.o
obj-$(CONFIG_AL_DMA) += al_dma_prep_pq.o
obj-$(CONFIG_AL_DMA) += al_dma_prep_pq_val.o

